{% set version = "1.5.3" %}
{% set sha256 = "98087a8c6198b9fedabbee10abaec52c3e1521cc52055148b7294b386550e5b8" %}
{% set variant = "openblas" %}

package:
  name: cycamore
  version: {{ version }}

source:
  fn: cycamore-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cycamore/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or py27 or py34 or (osx and py35)]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cyclus
  run:
    - python
    - cyclus

test:
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The Cyclus additional modules repository."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
