{% set version = "1.5.0" %}
{% set sha256 = "c7150ae9dfb40719a81a8c8afe3e7294cb6a3aa9fafca3601c061e1b712abc9f" %}
{% set variant = "openblas" %}

package:
  name: cycamore
  version: {{ version }}

source:
  fn: cycamore-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cycamore/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or py34]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - python
    - cmake
    - pkg-config
    - cyclus
  run:
    - cyclus

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The Cyclus additional modules repository."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
