travis:
  secure:
    BINSTAR_TOKEN: B4NpFcmmbM0uLGDIFTuG2F5C/ZfVQj4FtdsU9WwJVW4wkwi5phJdL/16DQd3ibfRB63yEU1xYJRkBfZKCSZqJocvXxvbcnmdwMUI8ZyffayTwhbZ643rBpTpjANxJytkGkTN8MZzszYy0pHcac3XAackXf6OJpfWx+veq6d+NG1nTfS50naLCGGvtgMEWQPzLB++DM52K9S1oLzAeKv1eQ+rxHWx+ronzxywR3EzzF7aPcYnRwqLdqKTpScfK6CSoY6y3RsiVP6G4lDsB4XlUaH/huPDbJJuyh5sy09UjewicMUEGh6VUkUTmFApoTlDty2ySLnyKmTrxvbRa5Duv9NvUM55g/3s1QGSU61dz/83p6ZBhH05WT3Elxbja6MMRHx4HdJhdPrH8bNHMHZ+AaB9CdsKmdTvbRqZQL0wsz1L8dL1FfnA7QcDm1X12ef356QcY1eg0kYjeOhcfUUuBOu3eC+5WTA7nleWRnv58Xib5Q+DfXov8evy15rjmeiT/upIb+sSSOU+2g4DYjd+Wsqi5woDwTnhHUjPEhd7YNB2itX4MZUMnGHSlZzTsg5ze1vT44wtG++1iKi7uCg7Ms3z3vi6+w+vNn2R2HQI9bNvu1OwwJ574LGjQwZ3i5KPSfvS0tNRsxNs0BFaZQQTqfcgcb3PgWWLeMuw3/tvLD8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
